=== Gregoor/openmensa/public/open-mensa-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://openmensa.org/open-mensa-v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://openmensa.org/open-mensa-v2" elementFormDefault="qualified">

    <xs:element name="openmensa" type="openmensaType"></xs:element>
    
    <xs:complexType name="openmensaType">
        <xs:annotation>
        	<xs:documentation>This is the required OpenMense root element always accompanied by a version attribute that explicitly tells the feed's version to the parser.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
    		<xs:element name="cafeteria" type="cafeteriaType"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="version" type="xs:float" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="cafeteriaType">
        <xs:annotation>
        	<xs:documentation>This stands for a single canteen.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="day" type="dayType" maxOccurs="unbounded"
    			minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="dayType">
    	<xs:sequence>
    		<xs:element name="category" type="categoryType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="date" use="required">
    		<xs:simpleType>
                <xs:annotation>
                	<xs:documentation>This field specifies the date of the day as "YYYY-MM-DD".</xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
    				<xs:pattern
    					value="[0-9]{4,4}-[0-9]{2,2}-[0-9]{2,2}">
    				</xs:pattern>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="categoryType">
    	<xs:sequence>
    		<xs:element name="meal" type="mealType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" use="required">
    		<xs:simpleType>
    			<xs:restriction base="xs:string">
    				<xs:minLength value="1"></xs:minLength>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="mealType">
    	<xs:sequence>
    		<xs:element name="name" type="xs:string"></xs:element>
    		<xs:element name="note" maxOccurs="unbounded" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="price" maxOccurs="unbounded" minOccurs="0" type="priceType">
                <xs:annotation>
                	<xs:documentation>This field contains a price in Euro for a meal.</xs:documentation>
                </xs:annotation>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
    	<xs:simpleContent>
    		<xs:extension base="xs:float">
    			<xs:attribute name="role" use="required">
    				<xs:simpleType>
    					<xs:restriction base="xs:string">
    						<xs:enumeration value="student"></xs:enumeration>
    						<xs:enumeration value="employee"></xs:enumeration>
    						<xs:enumeration value="other"></xs:enumeration>
    					</xs:restriction>
    				</xs:simpleType>
    			</xs:attribute>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== Gregoor/openmensa/spec/mocks/feed2_compact.xml
<?xml version="1.0" encoding="UTF-8"?><openmensa version="2.0" xmlns="http://openmensa.org/open-mensa-v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd"><canteen><day date="2012-09-03"><category name="Hauptgerichte"><meal><name>Putenbrust </name><note>Gefl체gel</note><price role="employee">2.50</price><price role="other">3.20</price><price role="student">1.45</price></meal><meal><name>Wirsingkohlroulade </name><note>Schwein</note><note>mit Phosphat</note><price role="employee">2.40</price><price role="other">3.10</price><price role="student">1.35</price></meal></category><category name="Beilagen"><meal><name>H채hnchengeschnetzeltes </name><note>Gefl체gel</note><price role="employee">2.50</price><price role="other">3.20</price><price role="student">1.45</price></meal><meal><name>Asiatische Gem체sepfanne mit Tofu und Glasnudeln</name><note>vegan</note><price role="employee">3.70</price><price role="other">4.75</price><price role="student">2.10</price></meal></category></day></canteen></openmensa>

=== Gregoor/openmensa/spec/mocks/feed2_doubleMeals.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0" xmlns="http://openmensa.org/open-mensa-v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd"><canteen><day date="2012-09-03">
	<category name="Wahlmen端 (Suppe)"><meal><name>Kartoffelsuppe mit Lauch</name></meal><meal><name>Kartoffelsuppe mit Lauch</name></meal></category>
	<category name="Wahlmen端 (Beilage)"><meal><name>Tagesangebot</name></meal></category>
	<category name="Wahlmen端 (Gem端se)"><meal><name>Tagesangebot</name></meal></category>
</day></canteen></openmensa>
